
# Preprocessing
```{r}
full.data <- read.csv("./cleaned_data.csv", header = TRUE, sep = ",")
df <- full.data

############################
## drop compression rate
############################
df <- subset(df, select = -c(compression.ratio))

############################
## drop stroke
############################
df <- subset(df, select = -c(stroke))

############################
## Construct area form width
## and length. Then drop
## redundant values
############################
df$area <- df$width * df$length

df <- subset(df, select = -c(width, length))

############################
## Construct area form width
## and length. Then drop
## redundant values
############################
df$mpg <- rowMeans(df[, c("city.mpg", "highway.mpg")], na.rm = TRUE)

df <- df[, !colnames(df) %in% c("city.mpg", "highway.mpg")]

############################
## drop insurance  data
############################
df <- subset(df, select = -c(normalized.losses, symboling))


categorial_vars.all <- c("make", "symboling", "fuel.type", "aspiration",
                         "num.of.doors", "body.style", "drive.wheels", "engine.location",
                         "engine.type", "num.of.cylinders", "fuel.system")

for (cat_var in categorial_vars.all) {
  if (cat_var %in% colnames(df)) {
    df[[cat_var]] <- as.factor(df[[cat_var]])
  }
}


numerical_vars.all <- c("normalized.losses", "wheel.base", "length", "width", "height",
                        "area", "crub.weight", "engine.size", "bore", "stroke",
                        "horsepower", "peak.rpm", "city.mpg", "highway.mpg", "mpg", "price")

for (num_var in numerical_vars.all) {
  if (num_var %in% colnames(df)) {
    df[[num_var]] <- as.numeric(as.character(df[[num_var]]))
  }
}

# Summary statistics
summary(df)

# Check for missing values
colSums(is.na(df))

```

```{r}
library(FactoMineR)
library(factoextra)
library(NbClust)

```


## HCPC
```{r}
numeric_df <- df[, sapply(df, is.numeric) & names(df) != "price"]

# Perform PCA on numeric variables
res.pca <- PCA(numeric_df, ncp = 2, graph = FALSE)

res.hcpc <- HCPC(res.pca, graph = FALSE)

# Dendrogram using fviz_dend
fviz_dend(res_hcpc.hcpc, rect = TRUE, rect_fill = TRUE, main="")

## 3D plot ##
plot(res.hcpc, choice = "3D.map")

# Visualization of Clusters
fviz_cluster(res.hcpc,
             geom = "point",
             repel = FALSE, 
             show.clust.cent = TRUE, 
             main = "")  # Exclude text labels
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```




































